# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PathFP.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PathFP.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cPathFP.proto\"\x88\x01\n\x02\x46P\x12\x0e\n\x06scanID\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x03\x12\x10\n\x08latitude\x18\x03 \x02(\x01\x12\x11\n\tlongitude\x18\x04 \x02(\x01\x12\x10\n\x08\x62uilding\x18\x05 \x02(\t\x12\x0b\n\x03mac\x18\x06 \x02(\t\x12\x0e\n\x06\x61pname\x18\x07 \x01(\t\x12\x0b\n\x03rss\x18\x08 \x02(\x05\"\x1d\n\x06PathFP\x12\x13\n\x06record\x18\x01 \x03(\x0b\x32\x03.FP')
)




_FP = _descriptor.Descriptor(
  name='FP',
  full_name='FP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scanID', full_name='FP.scanID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FP.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='FP.latitude', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='FP.longitude', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='building', full_name='FP.building', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='FP.mac', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apname', full_name='FP.apname', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rss', full_name='FP.rss', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=153,
)


_PATHFP = _descriptor.Descriptor(
  name='PathFP',
  full_name='PathFP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='PathFP.record', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=184,
)

_PATHFP.fields_by_name['record'].message_type = _FP
DESCRIPTOR.message_types_by_name['FP'] = _FP
DESCRIPTOR.message_types_by_name['PathFP'] = _PATHFP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FP = _reflection.GeneratedProtocolMessageType('FP', (_message.Message,), dict(
  DESCRIPTOR = _FP,
  __module__ = 'PathFP_pb2'
  # @@protoc_insertion_point(class_scope:FP)
  ))
_sym_db.RegisterMessage(FP)

PathFP = _reflection.GeneratedProtocolMessageType('PathFP', (_message.Message,), dict(
  DESCRIPTOR = _PATHFP,
  __module__ = 'PathFP_pb2'
  # @@protoc_insertion_point(class_scope:PathFP)
  ))
_sym_db.RegisterMessage(PathFP)


# @@protoc_insertion_point(module_scope)
